### PR TITLE
DS1052E firmware v00.04.04.00.00 50MHz with original docs, and 100MHz modded

### PR DESCRIPTION
**Pull request by lesliemanhu**
DS1052E firmware `v00.04.04.00.00` 50MHz non-modded with original docs, and 100MHz modded

### CODE REVIEW

**Comment by szafranski** [comment]
Nice! I assume tested and works? :)

**Comment by lesliemanhu** [comment]
Hi,

I don't have anything with such a high frequency that I can try the scope with (and I don't know if the hardware is even capable of measuring such high frequencies), but based on the system information and the "quick check" with the horizontal potentiometer (so it stops at 2.000ns), the modded FW works.

IMG_20240224_212953_k

IMG_20240225_121827_k

**Comment by szafranski** [comment]
Thanks!!!

**Comment by NuclearPhoenixx** [comment]
Worked for me as well, exactly like in your screenshots. Thanks! 👍🏻

(Btw, I'm amazed that I'm not the only one left using this ancient scope)

**Comment by szafranski** [comment]
It is very robust and popular model

**Comment by NuclearPhoenixx** [comment]
Oh yeah I like it, however, the encoders are really crap so there's that.

**Pull request merged**
